name: Documentation

on:   
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  documentation1:
    runs-on: ubuntu-latest
    name: Documentation Java
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version:  1.8

    - name: Make Documentation SystemDS Java
      run: mvn -P distribution package

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Java-documentation
        path: target/apidocs

  documentation2:
    runs-on: ubuntu-latest
    name: Documentation Python
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: 'x64'
        
    - name: Install Dependencies
      run: |
        cd src/main/python/docs
        python3 -m pip install -r requires-docs.txt

    - name: Make Documentation SystemDS-Python
      run: |
        cd src/main/python/docs
        make html

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: Python-documentation
        path: src/main/python/docs/build