name: Python Test

on: [push, pull_request]
  # push:
    # branches:
      # - master
  # pull_request:
    # branches:
      # - master

jobs:
  applicationsTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]
        java: [ 1.8 ]
    name:  Python Test
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Maven clean & package
      run: mvn clean package

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install pip Dependencies
      run: pip install numpy py4j wheel

    - name: Build Python Package
      # TODO: Find out how to make if statement correctly: suggestion but not working: if: ${{ matrix.tests }} == P
      run: |
        cd src/main/python
        python3 create_python_dist.py

    - name: Run all python tests
      run: |
        cd src/main/python
        python3 tests/test_l2svm.py
        python3 tests/test_matrix_aggregations.py
        python3 tests/test_matrix_binary_op.py
